Document xhost requirement, improve xhost error reporting
Refactored command execution functions into `util.rs`, created helper `run_command()`.

Output now if `xhost` is missing:
```
error: Error preparing X11: Failed to run xhost: No such file or directory (os error 2)
hint: Try installing package that contains command 'xhost'
```