fix(pulse): handle missing PulseAudio socket when directory exists (#190)
Handle correctly when the /run/user/1001/pulse directory exists but socket /run/user/1001/pulse/native does not.

After switching from user level pulseaudio to systemwide pulseaudio:

❯ ego -u a                      
error: Error preparing PulseAudio: '/run/user/1001/pulse/native': No such file or directory (os error 2)